AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla Fase 4 - IaC para Cuenta Personal

Resources:
  BucketDevOps:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "mi-bucket-devops-ia-${AWS::AccountId}"

  InstanciaEC2DevOps:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0e1bed4f06a3b463d
      KeyName: llave-devops
      Tags:
        - Key: Name
          Value: servidor-devops-iac
